version: '3.8'
services:
  app:
    build: .
    container_name: leaderboard_app
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      NEW_RELIC_CONFIG_FILE : /app/newrelic.ini
      NEW_RELIC_ENVIRONMENT : production

  celery:

    build: .
    command: newrelic-admin run-program celery -A app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
      - NEW_RELIC_ENVIRONMENT=production

  redis:
    image: redis:7-alpine

  db:
    image: postgres:14
    container_name: leaderboard_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaderboard
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'


volumes:
  postgres_data:
